name: Build Installer

on:
  push:
    branches:
      - 'main'

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: compile
        run: |
          mvn -B clean package
