name: Build Installer
run-name: Building push to main by @${{ github.actor }}

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mvn -B clean package
