name: Draft Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: compile
        run: |
          mvn -B clean package
      - id: release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref }} \
          --draft \
          --generate-notes \
          --title 'My Project ${{ github.ref }}' \
          target/*.jar
