name: Draft Release

on:
  push:
    tags:
      - 'release-*'

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: compile
        run: |
          mvn -B clean package
      - id: version
        run: echo "::set-output name=number::`echo "${{ github.ref }}" | sed 's/.*\/release-//'`"
      - id: release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref }} \
          --draft \
          --generate-notes \
          --title 'My Project ${{ steps.version.outputs.number }}' \
          target/*.jar
